// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("GuidIO")]
[assembly: AssemblyDescriptionAttribute("GuidIO manages the directory structure for files automatically based on the file name.")]
[assembly: AssemblyCompanyAttribute("Kai Timmermann")]
[assembly: AssemblyCopyrightAttribute("Copyright Kai Timmermann © 2015")]
[assembly: GuidAttribute("e20d9eef-3857-4661-b5ea-34f8bede1541")]
[assembly: AssemblyProductAttribute("GuidIO")]
[assembly: AssemblyVersionAttribute("0.1")]
[assembly: AssemblyFileVersionAttribute("0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1";
    }
}
